#include "Language.h"
#include "Assets.h"

Language::Select Language::language = Language::Select::Japanese;
GSuint Language::resolution_image = Image_ResolutionJP;
GSuint Language::screenmode_image = Image_ScreenModeJP;
GSuint Language::bgm_image = Image_BgmJP;
GSuint Language::se_image = Image_SeJP;
GSuint Language::language_image = Image_LanguageJP;
GSuint Language::check_control_image = Image_CheckControlJP;
GSuint Language::window_image = Image_WindowJP;
GSuint Language::fullscreen_image = Image_FullscreenJP;
GSuint Language::option_image = Image_OptionJP;
GSuint Language::play_icon_image = Image_PlayIconJP;
GSuint Language::option_icon_image = Image_OptionIconJP;
GSuint Language::quit_icon_image = Image_QuitIconJP;
GSuint Language::confirm_image = Image_ConfirmJP;
GSuint Language::weapon1_image = Image_WeaponOneJP;
GSuint Language::weapon2_image = Image_WeaponTwoJP;
GSuint Language::stage1_image = Image_StageOneJP;
GSuint Language::stage2_image = Image_StageTwoJP;
GSuint Language::stage3_image = Image_StageThreeJP;
GSuint Language::quest_stage1_image = Image_QuestStageOneJP;
GSuint Language::quest_stage2_image = Image_QuestStageTwoJP;
GSuint Language::quest_stage3_image = Image_QuestStageThreeJP;
GSuint Language::select_weapon_image = Image_SelectWeaponJP;
GSuint Language::select_reward_image = Image_SelectRewardJP;
GSuint Language::health_reward_image = Image_HealthRewardJP;
GSuint Language::stamina_reward_image = Image_StaminaRewardJP;
GSuint Language::speed_reward_image = Image_SpeedRewardJP;
GSuint Language::attack_reward_image = Image_AttackRewardJP;
GSuint Language::same_weapon_image = Image_SameWeaponJP;
GSuint Language::game_over_image = Image_GameOverJP;
GSuint Language::game_clear_image = Image_GameClearJP;
GSuint Language::apply_image = Image_ApplyJP;
GSuint Language::retry_image = Image_RetryJP;
GSuint Language::retry_reset_image = Image_RetryResetJP;
GSuint Language::next_image = Image_NextJP;
GSuint Language::result_image = Image_ResultJP;
GSuint Language::return_title_image = Image_ReturnTitleJP;
GSuint Language::time_spent_image = Image_TimeSpentJP;
GSuint Language::total_score_image = Image_TotalScoreJP;

void Language::change_language(Select language){
	switch (language){
	case Language::Select::English:
		Language::resolution_image = Image_ResolutionEN;
		Language::screenmode_image = Image_ScreenModeEN;
		Language::bgm_image = Image_BgmEN;
		Language::se_image = Image_SeEN;
		Language::language_image = Image_LanguageEN;
		Language::check_control_image = Image_CheckControlEN;
		Language::window_image = Image_WindowEN;
		Language::fullscreen_image = Image_FullscreenEN;
		Language::option_image = Image_OptionEN;
		Language::play_icon_image = Image_PlayIconEN;
		Language::option_icon_image = Image_OptionIconEN;
		Language::quit_icon_image = Image_QuitIconEN;
		Language::confirm_image = Image_ConfirmEN;
		Language::weapon1_image = Image_WeaponOneEN;
		Language::weapon2_image = Image_WeaponTwoEN;
		Language::stage1_image = Image_StageOneEN;
		Language::stage2_image = Image_StageTwoEN;
		Language::stage3_image = Image_StageThreeEN;
		Language::quest_stage1_image = Image_QuestStageOneEN;
		Language::quest_stage2_image = Image_QuestStageTwoEN;
		Language::quest_stage3_image = Image_QuestStageThreeEN;
		Language::select_weapon_image = Image_SelectWeaponEN;
		Language::select_reward_image = Image_SelectRewardEN;
		Language::health_reward_image = Image_HealthRewardEN;
		Language::stamina_reward_image = Image_StaminaRewardEN;
		Language::speed_reward_image = Image_SpeedRewardEN;
		Language::attack_reward_image = Image_AttackRewardEN;
		Language::same_weapon_image = Image_SameWeaponEN;
		Language::game_over_image = Image_GameOverEN;
		Language::game_clear_image = Image_GameClearEN;
		Language::apply_image = Image_ApplyEN;
		Language::retry_image = Image_RetryEN;
		Language::retry_reset_image = Image_RetryResetEN;
		Language::next_image = Image_NextEN;
		Language::result_image = Image_ResultEN;
		Language::return_title_image = Image_ReturnTitleEN;
		Language::time_spent_image = Image_TimeSpentEN;
		Language::total_score_image = Image_TotalScoreEN;
		break;
	case Language::Select::Japanese:
		Language::resolution_image = Image_ResolutionJP;
		Language::screenmode_image = Image_ScreenModeJP;
		Language::bgm_image = Image_BgmJP;
		Language::se_image = Image_SeJP;
		Language::language_image = Image_LanguageJP;
		Language::check_control_image = Image_CheckControlJP;
		Language::window_image = Image_WindowJP;
		Language::fullscreen_image = Image_FullscreenJP;
		Language::option_image = Image_OptionJP;
		Language::play_icon_image = Image_PlayIconJP;
		Language::option_icon_image = Image_OptionIconJP;
		Language::quit_icon_image = Image_QuitIconJP;
		Language::confirm_image = Image_ConfirmJP;
		Language::weapon1_image = Image_WeaponOneJP;
		Language::weapon2_image = Image_WeaponTwoJP;
		Language::stage1_image = Image_StageOneJP;
		Language::stage2_image = Image_StageTwoJP;
		Language::stage3_image = Image_StageThreeJP;
		Language::quest_stage1_image = Image_QuestStageOneJP;
		Language::quest_stage2_image = Image_QuestStageTwoJP;
		Language::quest_stage3_image = Image_QuestStageThreeJP;
		Language::select_weapon_image = Image_SelectWeaponJP;
		Language::select_reward_image = Image_SelectRewardJP;
		Language::health_reward_image = Image_HealthRewardJP;
		Language::stamina_reward_image = Image_StaminaRewardJP;
		Language::speed_reward_image = Image_SpeedRewardJP;
		Language::attack_reward_image = Image_AttackRewardJP;
		Language::same_weapon_image = Image_SameWeaponJP;
		Language::game_over_image = Image_GameOverJP;
		Language::game_clear_image = Image_GameClearJP;
		Language::apply_image = Image_ApplyJP;
		Language::retry_image = Image_RetryJP;
		Language::retry_reset_image = Image_RetryResetJP;
		Language::next_image = Image_NextJP;
		Language::result_image = Image_ResultJP;
		Language::return_title_image = Image_ReturnTitleJP;
		Language::time_spent_image = Image_TimeSpentJP;
		Language::total_score_image = Image_TotalScoreJP;
		break;
	}
}
