#ifndef PLAYER_MOTION_ID_H_
#define PLAYER_MOTION_ID_H_

// モーション番号
enum {
	// デフォルト
	MotionDefaultJump00B = 0,
	MotionDefaultJump01B = 1,
	MotionDefaultHandUp = 2,
	MotionDefaultJump00 = 3,
	MotionDefaultJump01 = 4,
	MotionDefaultRunF = 5,
	MotionDefaultRunL = 6,
	MotionDefaultRunR = 7,
	MotionDefaultSlide = 8,
	MotionDefaultUmatobi = 9,
	MotionDefaultWait00 = 10,
	MotionDefaultWait01 = 11,
	MotionDefaultWait02 = 12,
	MotionDefaultWait03 = 13,
	MotionDefaultWait04 = 14,
	MotionDefaultWalkB = 15,
	MotionDefaultWalkF = 16,
	MotionDefaultWalkL = 17,
	MotionDefaultWalkR = 18,
	MotionDefaultWin = 19,
	MotionDefaultLose = 20,
	MotionDefaultDamage0 = 21,
	MotionDefaultDamage1 = 22,
	MotionDefaultReflesh = 23,

	// 斧
	MotionAxeEquip = 24,
	MotionAxeAttack1 = 25,
	MotionAxeAttack2 = 26,
	MotionAxeAttack3 = 27,
	MotionAxeSkill = 33,
	MotionAxeSkill1 = 33,
	MotionAxeSkill2 = 34,
	MotionAxeSkill3 = 35,
	MotionAxeGuard = 37,
	MotionAxeIdle = 36,
	MotionAxeRunF = 29,
	MotionAxeWalkF = 30,
	MotionAxeWalkB = 31,
	MotionAxeJump = 32,
	MotionAxeDamage = 28,
	MotionAxeDie = 38,
	
	//剣盾
	MotionSwordShieldEquip = 39,
	MotionSwordShieldAttack1 = 40,
	MotionSwordShieldAttack2 = 41,
	MotionSwordShieldAttack3 = 42,
	MotionSwordShieldSkill = 49,
	MotionSwordShieldSkill1 = 48,
	MotionSwordShieldSkill2 = 49,
	MotionSwordShieldSkill3 = 50,
	MotionSwordShieldGuard = 52,
	MotionSwordShieldIdle = 51,
	MotionSwordShieldRunF = 44,
	MotionSwordShieldWalkF = 45,
	MotionSwordShieldWalkB = 46,
	MotionSwordShieldJump = 47,
	MotionSwordShieldDamage = 43,
	MotionSwordShieldDie = 53,

	// 大検
	MotionGreatSwordEquip = 54,
	MotionGreatSwordAttack1 = 55,
	MotionGreatSwordAttack2 = 56,
	MotionGreatSwordAttack3 = 57,
	MotionGreatSwordSkill = 63,
	MotionGreatSwordSkill1 = 63,
	MotionGreatSwordSkill2 = 64,
	MotionGreatSwordSkill3 = 65,
	MotionGreatSwordGuard = 67,
	MotionGreatSwordIdle = 66,
	MotionGreatSwordRunF = 59,
	MotionGreatSwordWalkF = 60,
	MotionGreatSwordWalkB = 61,
	MotionGreatSwordJump = 62,
	MotionGreatSwordDamage = 58,
	MotionGreatSwordDie = 68,

	// 魔法
	MotionMagicEquip = 69,
	MotionMagicRunF = 70,
	MotionMagicWalkF = 71,
	MotionMagicWalkB = 72,
	MotionMagicJump = 82,
	MotionMagicAttack1 = 73,
	MotionMagicAttack2 = 74,
	MotionMagicSkill1 = 75,
	MotionMagicSkill2 = 76,
	MotionMagicSkill3 = 77,
	MotionMagicGuard = 80,
	MotionMagicIdle = 81,
	MotionMagicDamage = 78,
	MotionMagicKnockback = 83,
	MotionMagicDie = 79,

	// 銃共通
	MotionGunEquip = 84,
	MotionGunRunF = 85,
	MotionGunWalkF = 86,
	MotionGunWalkB = 87,
	MotionGunJump = 96,
	MotionGunDamage = 88,
	MotionGunDie = 89,
	MotionGunKnockback = 90,
	MotionGunIdle = 95,
	MotionGunEvadeF = 91,
	MotionGunEvadeB = 92,
	MotionGunEvadeL = 93,
	MotionGunEvadeR = 94,
	MotionGunBuff = 112,
	MotionGunGuard = 113,

	// ピストル
	MotionPistolAim = 97,
	MotionPistolFire = 98,
	MotionPistolSkill = 100,
	MotionPistolSkill1 = 99,
	MotionPistolSkill2 = 100,
	MotionPistolAimRun = 101,
	
	// ライフル
	MotionRifleAim = 102,
	MotionRifleFire = 103,
	MotionRifleSkill = 105,
	MotionRifleSkill1 = 104,
	MotionRifleSkill2 = 105,
	MotionRifleAimRun = 106,

	// ショットガン
	MotionShotgunAim = 107,
	MotionShotgunFire = 108,
	MotionShotgunSkill = 110,
	MotionShotgunSkill1 = 109,
	MotionShotgunSkill2 = 110,
	MotionShotgunAimRun = 111,
};

#endif